# Criando um xarray Dataset a partir de dados sintéticos

## Importando os módulos principais

In [1]:
import numpy as np

In [2]:
import xarray as xr

In [4]:
import pandas as pd

## Criando as coordenadas temporal e espacial

### Latitudes

In [27]:
lats = np.linspace(-90,90,320)

In [29]:
print("lats:\n",lats)

lats:
 [-90.         -89.43573668 -88.87147335 -88.30721003 -87.74294671
 -87.17868339 -86.61442006 -86.05015674 -85.48589342 -84.92163009
 -84.35736677 -83.79310345 -83.22884013 -82.6645768  -82.10031348
 -81.53605016 -80.97178683 -80.40752351 -79.84326019 -79.27899687
 -78.71473354 -78.15047022 -77.5862069  -77.02194357 -76.45768025
 -75.89341693 -75.32915361 -74.76489028 -74.20062696 -73.63636364
 -73.07210031 -72.50783699 -71.94357367 -71.37931034 -70.81504702
 -70.2507837  -69.68652038 -69.12225705 -68.55799373 -67.99373041
 -67.42946708 -66.86520376 -66.30094044 -65.73667712 -65.17241379
 -64.60815047 -64.04388715 -63.47962382 -62.9153605  -62.35109718
 -61.78683386 -61.22257053 -60.65830721 -60.09404389 -59.52978056
 -58.96551724 -58.40125392 -57.8369906  -57.27272727 -56.70846395
 -56.14420063 -55.5799373  -55.01567398 -54.45141066 -53.88714734
 -53.32288401 -52.75862069 -52.19435737 -51.63009404 -51.06583072
 -50.5015674  -49.93730408 -49.37304075 -48.80877743 -48.24451411
 -47.68025078 -47.11598746 -46.55172414 -45.98746082 -45.42319749
 -44.85893417 -44.29467085 -43.73040752 -43.1661442  -42.60188088
 -42.03761755 -41.47335423 -40.90909091 -40.34482759 -39.78056426
 -39.21630094 -38.65203762 -38.08777429 -37.52351097 -36.95924765
 -36.39498433 -35.830721   -35.26645768 -34.70219436 -34.13793103
 -33.57366771 -33.00940439 -32.44514107 -31.88087774 -31.31661442
 -30.7523511  -30.18808777 -29.62382445 -29.05956113 -28.49529781
 -27.93103448 -27.36677116 -26.80250784 -26.23824451 -25.67398119
 -25.10971787 -24.54545455 -23.98119122 -23.4169279  -22.85266458
 -22.28840125 -21.72413793 -21.15987461 -20.59561129 -20.03134796
 -19.46708464 -18.90282132 -18.33855799 -17.77429467 -17.21003135
 -16.64576803 -16.0815047  -15.51724138 -14.95297806 -14.38871473
 -13.82445141 -13.26018809 -12.69592476 -12.13166144 -11.56739812
 -11.0031348  -10.43887147  -9.87460815  -9.31034483  -8.7460815
  -8.18181818  -7.61755486  -7.05329154  -6.48902821  -5.92476489
  -5.36050157  -4.79623824  -4.23197492  -3.6677116   -3.10344828
  -2.53918495  -1.97492163  -1.41065831  -0.84639498  -0.28213166
   0.28213166   0.84639498   1.41065831   1.97492163   2.53918495
   3.10344828   3.6677116    4.23197492   4.79623824   5.36050157
   5.92476489   6.48902821   7.05329154   7.61755486   8.18181818
   8.7460815    9.31034483   9.87460815  10.43887147  11.0031348
  11.56739812  12.13166144  12.69592476  13.26018809  13.82445141
  14.38871473  14.95297806  15.51724138  16.0815047   16.64576803
  17.21003135  17.77429467  18.33855799  18.90282132  19.46708464
  20.03134796  20.59561129  21.15987461  21.72413793  22.28840125
  22.85266458  23.4169279   23.98119122  24.54545455  25.10971787
  25.67398119  26.23824451  26.80250784  27.36677116  27.93103448
  28.49529781  29.05956113  29.62382445  30.18808777  30.7523511
  31.31661442  31.88087774  32.44514107  33.00940439  33.57366771
  34.13793103  34.70219436  35.26645768  35.830721    36.39498433
  36.95924765  37.52351097  38.08777429  38.65203762  39.21630094
  39.78056426  40.34482759  40.90909091  41.47335423  42.03761755
  42.60188088  43.1661442   43.73040752  44.29467085  44.85893417
  45.42319749  45.98746082  46.55172414  47.11598746  47.68025078
  48.24451411  48.80877743  49.37304075  49.93730408  50.5015674
  51.06583072  51.63009404  52.19435737  52.75862069  53.32288401
  53.88714734  54.45141066  55.01567398  55.5799373   56.14420063
  56.70846395  57.27272727  57.8369906   58.40125392  58.96551724
  59.52978056  60.09404389  60.65830721  61.22257053  61.78683386
  62.35109718  62.9153605   63.47962382  64.04388715  64.60815047
  65.17241379  65.73667712  66.30094044  66.86520376  67.42946708
  67.99373041  68.55799373  69.12225705  69.68652038  70.2507837
  70.81504702  71.37931034  71.94357367  72.50783699  73.07210031
  73.63636364  74.20062696  74.76489028  75.32915361  75.89341693
  76.45768025  77.02194357  77.5862069   78.15047022  78.71473354
  79.27899687  79.84326019  80.40752351  80.97178683  81.53605016
  82.10031348  82.6645768   83.22884013  83.79310345  84.35736677
  84.92163009  85.48589342  86.05015674  86.61442006  87.17868339
  87.74294671  88.30721003  88.87147335  89.43573668  90.        ]

### Longitudes

In [31]:
lons = np.linspace(0,360,641)

In [32]:
print("lons:\n",lons)

lons:
 [  0.       0.5625   1.125    1.6875   2.25     2.8125   3.375    3.9375
   4.5      5.0625   5.625    6.1875   6.75     7.3125   7.875    8.4375
   9.       9.5625  10.125   10.6875  11.25    11.8125  12.375   12.9375
  13.5     14.0625  14.625   15.1875  15.75    16.3125  16.875   17.4375
  18.      18.5625  19.125   19.6875  20.25    20.8125  21.375   21.9375
  22.5     23.0625  23.625   24.1875  24.75    25.3125  25.875   26.4375
  27.      27.5625  28.125   28.6875  29.25    29.8125  30.375   30.9375
  31.5     32.0625  32.625   33.1875  33.75    34.3125  34.875   35.4375
  36.      36.5625  37.125   37.6875  38.25    38.8125  39.375   39.9375
  40.5     41.0625  41.625   42.1875  42.75    43.3125  43.875   44.4375
  45.      45.5625  46.125   46.6875  47.25    47.8125  48.375   48.9375
  49.5     50.0625  50.625   51.1875  51.75    52.3125  52.875   53.4375
  54.      54.5625  55.125   55.6875  56.25    56.8125  57.375   57.9375
  58.5     59.0625  59.625   60.1875  60.75    61.3125  61.875   62.4375
  63.      63.5625  64.125   64.6875  65.25    65.8125  66.375   66.9375
  67.5     68.0625  68.625   69.1875  69.75    70.3125  70.875   71.4375
  72.      72.5625  73.125   73.6875  74.25    74.8125  75.375   75.9375
  76.5     77.0625  77.625   78.1875  78.75    79.3125  79.875   80.4375
  81.      81.5625  82.125   82.6875  83.25    83.8125  84.375   84.9375
  85.5     86.0625  86.625   87.1875  87.75    88.3125  88.875   89.4375
  90.      90.5625  91.125   91.6875  92.25    92.8125  93.375   93.9375
  94.5     95.0625  95.625   96.1875  96.75    97.3125  97.875   98.4375
  99.      99.5625 100.125  100.6875 101.25   101.8125 102.375  102.9375
 103.5    104.0625 104.625  105.1875 105.75   106.3125 106.875  107.4375
 108.     108.5625 109.125  109.6875 110.25   110.8125 111.375  111.9375
 112.5    113.0625 113.625  114.1875 114.75   115.3125 115.875  116.4375
 117.     117.5625 118.125  118.6875 119.25   119.8125 120.375  120.9375
 121.5    122.0625 122.625  123.1875 123.75   124.3125 124.875  125.4375
 126.     126.5625 127.125  127.6875 128.25   128.8125 129.375  129.9375
 130.5    131.0625 131.625  132.1875 132.75   133.3125 133.875  134.4375
 135.     135.5625 136.125  136.6875 137.25   137.8125 138.375  138.9375
 139.5    140.0625 140.625  141.1875 141.75   142.3125 142.875  143.4375
 144.     144.5625 145.125  145.6875 146.25   146.8125 147.375  147.9375
 148.5    149.0625 149.625  150.1875 150.75   151.3125 151.875  152.4375
 153.     153.5625 154.125  154.6875 155.25   155.8125 156.375  156.9375
 157.5    158.0625 158.625  159.1875 159.75   160.3125 160.875  161.4375
 162.     162.5625 163.125  163.6875 164.25   164.8125 165.375  165.9375
 166.5    167.0625 167.625  168.1875 168.75   169.3125 169.875  170.4375
 171.     171.5625 172.125  172.6875 173.25   173.8125 174.375  174.9375
 175.5    176.0625 176.625  177.1875 177.75   178.3125 178.875  179.4375
 180.     180.5625 181.125  181.6875 182.25   182.8125 183.375  183.9375
 184.5    185.0625 185.625  186.1875 186.75   187.3125 187.875  188.4375
 189.     189.5625 190.125  190.6875 191.25   191.8125 192.375  192.9375
 193.5    194.0625 194.625  195.1875 195.75   196.3125 196.875  197.4375
 198.     198.5625 199.125  199.6875 200.25   200.8125 201.375  201.9375
 202.5    203.0625 203.625  204.1875 204.75   205.3125 205.875  206.4375
 207.     207.5625 208.125  208.6875 209.25   209.8125 210.375  210.9375
 211.5    212.0625 212.625  213.1875 213.75   214.3125 214.875  215.4375
 216.     216.5625 217.125  217.6875 218.25   218.8125 219.375  219.9375
 220.5    221.0625 221.625  222.1875 222.75   223.3125 223.875  224.4375
 225.     225.5625 226.125  226.6875 227.25   227.8125 228.375  228.9375
 229.5    230.0625 230.625  231.1875 231.75   232.3125 232.875  233.4375
 234.     234.5625 235.125  235.6875 236.25   236.8125 237.375  237.9375
 238.5    239.0625 239.625  240.1875 240.75   241.3125 241.875  242.4375
 243.     243.5625 244.125  244.6875 245.25   245.8125 246.375  246.9375
 247.5    248.0625 248.625  249.1875 249.75   250.3125 250.875  251.4375
 252.     252.5625 253.125  253.6875 254.25   254.8125 255.375  255.9375
 256.5    257.0625 257.625  258.1875 258.75   259.3125 259.875  260.4375
 261.     261.5625 262.125  262.6875 263.25   263.8125 264.375  264.9375
 265.5    266.0625 266.625  267.1875 267.75   268.3125 268.875  269.4375
 270.     270.5625 271.125  271.6875 272.25   272.8125 273.375  273.9375
 274.5    275.0625 275.625  276.1875 276.75   277.3125 277.875  278.4375
 279.     279.5625 280.125  280.6875 281.25   281.8125 282.375  282.9375
 283.5    284.0625 284.625  285.1875 285.75   286.3125 286.875  287.4375
 288.     288.5625 289.125  289.6875 290.25   290.8125 291.375  291.9375
 292.5    293.0625 293.625  294.1875 294.75   295.3125 295.875  296.4375
 297.     297.5625 298.125  298.6875 299.25   299.8125 300.375  300.9375
 301.5    302.0625 302.625  303.1875 303.75   304.3125 304.875  305.4375
 306.     306.5625 307.125  307.6875 308.25   308.8125 309.375  309.9375
 310.5    311.0625 311.625  312.1875 312.75   313.3125 313.875  314.4375
 315.     315.5625 316.125  316.6875 317.25   317.8125 318.375  318.9375
 319.5    320.0625 320.625  321.1875 321.75   322.3125 322.875  323.4375
 324.     324.5625 325.125  325.6875 326.25   326.8125 327.375  327.9375
 328.5    329.0625 329.625  330.1875 330.75   331.3125 331.875  332.4375
 333.     333.5625 334.125  334.6875 335.25   335.8125 336.375  336.9375
 337.5    338.0625 338.625  339.1875 339.75   340.3125 340.875  341.4375
 342.     342.5625 343.125  343.6875 344.25   344.8125 345.375  345.9375
 346.5    347.0625 347.625  348.1875 348.75   349.3125 349.875  350.4375
 351.     351.5625 352.125  352.6875 353.25   353.8125 354.375  354.9375
 355.5    356.0625 356.625  357.1875 357.75   358.3125 358.875  359.4375
 360.    ]

### Tempos

In [33]:
times = pd.date_range("2014-11-01",periods=4)

In [34]:
print("times:\n",times)

times:
 DatetimeIndex(['2014-11-01', '2014-11-02', '2014-11-03', '2014-11-04'], dtype='datetime64[ns]', freq='D')

## Criando um array de dados sintéticos

Aqui deveremos criar um array que possua as dimensões temporal e espacial que definimos anteriormente. Para isso, utilizamos o tamanho destes arrays:

In [44]:
tmpvar = 15 + 8 * np.random.randn(len(times),len(lons),len(lats))

In [45]:
print("tmpvar:\n",tmpvar)

tmpvar:
 [[[20.23152403 16.46161902 12.50700463 ...  3.87581107 -1.89963194
    6.30090415]
  [17.86166355  8.25916669 21.529279   ... 16.58651488  8.45888622
    9.72509464]
  [ 4.48669903 18.1619333   8.10038706 ...  8.81936472  9.5004539
    7.07441812]
  ...
  [34.15020166  9.0029629  17.62032037 ... 21.3348045  24.62480801
   12.719267  ]
  [20.64384799 11.02374536  6.94788123 ...  6.92821607 24.60789144
   29.5228278 ]
  [26.20239932 31.26233518  5.7119261  ... 28.79821822 21.4898335
   20.46938951]]

 [[ 9.93329189  3.72693704 -0.8489019  ... 20.1043803  18.28204737
   18.15168154]
  [ 2.24452202 28.14332436 21.3437838  ... 14.76646335 16.75857444
   18.24294792]
  [ 9.49173585 21.53624132 11.60377171 ... 17.4012787  17.61161162
   21.1078093 ]
  ...
  [12.6195886   5.34606521 21.84627509 ... 15.14686589 -5.95480991
   19.9461389 ]
  [13.7841958   7.13996328 12.73249644 ... 21.87749518 14.22054288
   12.96184267]
  [16.25322792 19.61231346 17.40041273 ...  0.92241689  4.05707269
    8.54638172]]

 [[10.54909816 19.75194181 16.27631956 ... 14.65004563 12.72620078
    2.65772437]
  [18.15046786 17.7620491   7.85748387 ... 10.74568412 30.44881806
    9.83548877]
  [ 3.42462284 20.08455279 12.65498823 ... 13.48493262 18.60575635
   19.92595367]
  ...
  [ 8.05855436 18.64012277  9.3987627  ...  9.21926678 17.58101343
   25.88270492]
  [ 5.2794688   9.5628467  15.1484659  ... 16.60118584  7.59365661
   15.36688239]
  [ 9.49640852 18.51304617 14.55214783 ... 18.32112112  5.94190247
   18.68009418]]

 [[ 3.64324728 16.97223839 19.99587502 ... -3.19361695 17.56196868
   21.38880969]
  [26.40701991  0.84101731 20.31772987 ... 22.08878751 14.66220814
   33.92700001]
  [13.91032445 25.87998323 20.70119618 ... 18.38617471  7.38746707
   13.1607936 ]
  ...
  [17.76855178  0.78846395 18.77286291 ... 14.39363478 25.42407945
   18.28294195]
  [20.11758435 -5.42184219  8.99804278 ... 11.48290955 -2.10362628
    7.54861166]
  [ 8.04825222  8.28467539 13.60298594 ... 11.55886077 19.19544373
   10.09409656]]]

Ou seja, o array "tmpvar" possui dimensões "len(time)" x "len(lon)" x "len(lat)".

### Criando o Dataset

Inicializando o Dataset:

In [51]:
ds = xr.Dataset()

In [52]:
ds

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

Adicionando a variável "tmpvar" ao Dataset. Observe que a ordem das dimensões deve ser a mesma que indexa a variável "tmpvar":

In [54]:
ds["tmpvar"] = (("time","lon","lat"),tmpvar)

In [55]:
ds

<xarray.Dataset>
Dimensions:  (lat: 320, lon: 641, time: 4)
Dimensions without coordinates: lat, lon, time
Data variables:
    tmpvar   (time, lon, lat) float64 20.23 16.46 12.51 ... 11.56 19.2 10.09

Adicionando as coordenadas espaciais:

In [56]:
ds.coords["lat"] = ("lat",lats)

In [57]:
ds

<xarray.Dataset>
Dimensions:  (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat      (lat) float64 -90.0 -89.44 -88.87 -88.31 ... 88.31 88.87 89.44 90.0
Dimensions without coordinates: lon, time
Data variables:
    tmpvar   (time, lon, lat) float64 20.23 16.46 12.51 ... 11.56 19.2 10.09

In [58]:
ds.coords["lon"] = ("lon",lons)

In [59]:
ds

<xarray.Dataset>
Dimensions:  (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat      (lat) float64 -90.0 -89.44 -88.87 -88.31 ... 88.31 88.87 89.44 90.0
  * lon      (lon) float64 0.0 0.5625 1.125 1.688 ... 358.3 358.9 359.4 360.0
Dimensions without coordinates: time
Data variables:
    tmpvar   (time, lon, lat) float64 20.23 16.46 12.51 ... 11.56 19.2 10.09

Adicionando a coordenada temporal:

In [60]:
ds.coords["time"] = times

In [61]:
ds

<xarray.Dataset>
Dimensions:  (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat      (lat) float64 -90.0 -89.44 -88.87 -88.31 ... 88.31 88.87 89.44 90.0
  * lon      (lon) float64 0.0 0.5625 1.125 1.688 ... 358.3 358.9 359.4 360.0
  * time     (time) datetime64[ns] 2014-11-01 2014-11-02 2014-11-03 2014-11-04
Data variables:
    tmpvar   (time, lon, lat) float64 20.23 16.46 12.51 ... 11.56 19.2 10.09

Adicionando um tempo de referência:

In [62]:
ds.coords["reference_time"] = pd.Timestamp("2014-10-31")

In [64]:
ds

<xarray.Dataset>
Dimensions:         (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat             (lat) float64 -90.0 -89.44 -88.87 ... 88.87 89.44 90.0
  * lon             (lon) float64 0.0 0.5625 1.125 1.688 ... 358.9 359.4 360.0
  * time            (time) datetime64[ns] 2014-11-01 2014-11-02 ... 2014-11-04
    reference_time  datetime64[ns] 2014-10-31
Data variables:
    tmpvar          (time, lon, lat) float64 20.23 16.46 12.51 ... 19.2 10.09

Adicionando metadados que ajudam a descrever as variáveis:

In [66]:
ds.attrs["title"] = "Absolute Temperature"

In [67]:
ds

<xarray.Dataset>
Dimensions:         (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat             (lat) float64 -90.0 -89.44 -88.87 ... 88.87 89.44 90.0
  * lon             (lon) float64 0.0 0.5625 1.125 1.688 ... 358.9 359.4 360.0
  * time            (time) datetime64[ns] 2014-11-01 2014-11-02 ... 2014-11-04
    reference_time  datetime64[ns] 2014-10-31
Data variables:
    tmpvar          (time, lon, lat) float64 20.23 16.46 12.51 ... 19.2 10.09
Attributes:
    title:    Absolute Temperature

In [68]:
ds.attrs["unit"] = "Degrees Celsius"

In [69]:
ds

<xarray.Dataset>
Dimensions:         (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat             (lat) float64 -90.0 -89.44 -88.87 ... 88.87 89.44 90.0
  * lon             (lon) float64 0.0 0.5625 1.125 1.688 ... 358.9 359.4 360.0
  * time            (time) datetime64[ns] 2014-11-01 2014-11-02 ... 2014-11-04
    reference_time  datetime64[ns] 2014-10-31
Data variables:
    tmpvar          (time, lon, lat) float64 20.23 16.46 12.51 ... 19.2 10.09
Attributes:
    title:    Absolute Temperature
    unit:     Degrees Celsius

In [76]:
ds.attrs["resolution"] = 360 / (len(lon)-1)

In [77]:
ds

<xarray.Dataset>
Dimensions:         (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat             (lat) float64 -90.0 -89.44 -88.87 ... 88.87 89.44 90.0
  * lon             (lon) float64 0.0 0.5625 1.125 1.688 ... 358.9 359.4 360.0
  * time            (time) datetime64[ns] 2014-11-01 2014-11-02 ... 2014-11-04
    reference_time  datetime64[ns] 2014-10-31
Data variables:
    tmpvar          (time, lon, lat) float64 20.23 16.46 12.51 ... 19.2 10.09
Attributes:
    title:       Absolute Temperature
    unit:        Degrees Celsius
    resolution:  0.5625

### Acrescentando uma nova variável (com as mesmas dimensões)

In [91]:
tmpvar2 = 1005 + np.random.randn(len(time),len(lon),len(lat))

In [92]:
print("tmpvar2:\n",tmpvar2)

tmpvar2:
 [[[1004.99613901 1006.12102585 1005.93411186 ... 1003.33184502
   1005.13032353 1003.61297746]
  [1004.66057644 1005.31397722 1004.4772732  ... 1003.45443012
   1005.86832166 1005.79097357]
  [1003.40748908 1006.22100942 1003.90138814 ... 1004.58410498
   1005.73083301 1003.44634031]
  ...
  [1005.48058873 1004.37132758 1003.27431544 ... 1004.63357604
   1004.8140959  1004.74494668]
  [1004.37045553 1003.43721821 1004.05936659 ... 1005.84680362
   1005.13260767 1005.71334181]
  [1004.3046657  1005.59621221 1005.10679608 ... 1005.43970557
   1006.60466972 1005.07145339]]

 [[1004.60794255 1004.83629149 1004.82933918 ... 1003.3305867
   1004.33912859 1005.39198463]
  [1005.72224311 1004.81543447 1004.03886741 ... 1002.20669754
   1005.61096706 1006.90580757]
  [1005.22257837 1003.19380201 1004.99345206 ... 1004.92968103
   1004.55110556 1006.82302846]
  ...
  [1004.30591427 1004.17217913 1004.83182652 ... 1005.25773648
   1003.9321745  1005.2568774 ]
  [1005.20840993 1004.91569197 1004.63982633 ... 1005.0333621
   1003.24137164 1006.14717921]
  [1005.63976181 1006.0923     1005.41950548 ... 1004.82679428
   1006.27001336 1005.54457499]]

 [[1004.2311928  1004.47949077 1004.94893145 ... 1003.85547493
   1005.14925861 1006.36359328]
  [1004.24798311 1004.87086499 1003.56708027 ... 1005.39416935
   1004.30739416 1006.64455307]
  [1004.38712495 1006.96818361 1003.93086504 ... 1004.47460784
   1004.48788058 1005.47240064]
  ...
  [1004.48370438 1005.10358298 1004.97191251 ... 1003.98906888
   1004.2249939  1005.5440588 ]
  [1003.53275244 1005.05487001 1005.31336771 ... 1004.39859386
   1004.65288339 1004.89365742]
  [1003.84109828 1005.72483515 1004.97017203 ... 1006.2378423
   1004.39505846 1004.61686857]]

 [[1005.70789817 1004.10125752 1005.95626591 ... 1005.02385622
   1006.93720526 1005.28265868]
  [1005.30934348 1005.01927877 1004.00384386 ... 1004.87827695
   1006.9197525  1005.05223381]
  [1004.75337043 1004.86552448 1003.6068509  ... 1005.2185885
   1005.1651603  1003.11721518]
  ...
  [1004.53734864 1005.37962539 1005.38339319 ... 1004.32212205
   1004.56308798 1004.97729327]
  [1003.56756257 1004.50133518 1005.91699994 ... 1005.25390351
   1005.32201193 1003.79409888]
  [1006.00763273 1004.49299039 1004.67924758 ... 1004.86908473
   1004.18379915 1005.51718656]]]

Acrescentando a variável "tmpvar2" ao Dataset "ds":

In [93]:
ds["tmpvar2"] = (("time","lon","lat"),tmpvar2)

In [94]:
ds

<xarray.Dataset>
Dimensions:         (lat: 320, lon: 641, time: 4)
Coordinates:
  * lat             (lat) float64 -90.0 -89.44 -88.87 ... 88.87 89.44 90.0
  * lon             (lon) float64 0.0 0.5625 1.125 1.688 ... 358.9 359.4 360.0
  * time            (time) datetime64[ns] 2014-11-01 2014-11-02 ... 2014-11-04
    reference_time  datetime64[ns] 2014-10-31
Data variables:
    tmpvar          (time, lon, lat) float64 20.23 16.46 12.51 ... 19.2 10.09
    tmpvar2         (time, lon, lat) float64 1.005e+03 1.006e+03 ... 1.006e+03
Attributes:
    title:       Absolute Temperature
    unit:        Degrees Celsius
    resolution:  0.5625